// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmUhnUxGgeci0rY02Qnk6srOqxzV3R6E',
    appId: '1:350508885608:web:1531515bc23d3d716c3ddd',
    messagingSenderId: '350508885608',
    projectId: 'task-manager-6',
    authDomain: 'task-manager-6.firebaseapp.com',
    storageBucket: 'task-manager-6.firebasestorage.app',
    measurementId: 'G-N6NYFVKK4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApHBY2_3Yb8p7GUoLOOfjwXI-sc4xywU8',
    appId: '1:350508885608:android:8cb5ce4a9f61d3836c3ddd',
    messagingSenderId: '350508885608',
    projectId: 'task-manager-6',
    storageBucket: 'task-manager-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAe-SUYNaypSw_zdJ75mEwu4N-VU-dt0',
    appId: '1:350508885608:ios:51dbf2b1ea79787e6c3ddd',
    messagingSenderId: '350508885608',
    projectId: 'task-manager-6',
    storageBucket: 'task-manager-6.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAe-SUYNaypSw_zdJ75mEwu4N-VU-dt0',
    appId: '1:350508885608:ios:51dbf2b1ea79787e6c3ddd',
    messagingSenderId: '350508885608',
    projectId: 'task-manager-6',
    storageBucket: 'task-manager-6.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBmUhnUxGgeci0rY02Qnk6srOqxzV3R6E',
    appId: '1:350508885608:web:6442fe162bef5b996c3ddd',
    messagingSenderId: '350508885608',
    projectId: 'task-manager-6',
    authDomain: 'task-manager-6.firebaseapp.com',
    storageBucket: 'task-manager-6.firebasestorage.app',
    measurementId: 'G-013DS5MDDK',
  );
}
